# Generated by Django 2.1.4 on 2019-01-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(verbose_name='商品数量')),
            ],
            options={
                'verbose_name_plural': '订单详情',
                'verbose_name': '订单详情',
                'db_table': 'order_detail',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('order_time', models.DateTimeField(blank=True, null=True, verbose_name='下单时间')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='订单金额')),
                ('coupon_id', models.IntegerField(blank=True, null=True, verbose_name='优惠券ID')),
                ('status', models.CharField(blank=True, choices=[('1', '等待商家接单'), ('2', '配送中'), ('3', '已送达'), ('4', '订单已取消')], default='1', max_length=1, null=True, verbose_name='订单状态')),
            ],
            options={
                'verbose_name_plural': '订单管理',
                'verbose_name': '订单管理',
                'db_table': 'order_info',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='商品价格')),
                ('groups', models.CharField(max_length=20, verbose_name='商品分类')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品描述')),
                ('image', models.ImageField(default='image/default.png', upload_to='image/product')),
            ],
            options={
                'verbose_name_plural': '商品管理',
                'verbose_name': '商品管理',
                'db_table': 'product_detail',
            },
        ),
    ]
