# Generated by Django 2.1.4 on 2019-01-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190101_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '订单列表', 'verbose_name_plural': '订单列表'},
        ),
        migrations.AlterModelOptions(
            name='productdetail',
            options={'verbose_name': '商品列表', 'verbose_name_plural': '商品列表'},
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='image',
            field=models.ImageField(default='default.png', upload_to='product', verbose_name='产品图片'),
        ),
    ]
